services:
  novelhub:
    image: azenkain/novel-hub:latest
    container_name: novelhub
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 3434
      DATA_DIR: /data
      TRUST_PROXY: ${TRUST_PROXY:-true}
      RESTORE_AUTO_RESTART: ${RESTORE_AUTO_RESTART:-true}

    ports:
      - "${SERVER_PORT:-3434}:3434"
    volumes:
      - novelhub_data:/data

volumes:
  novelhub_data:
