package main

import (
	"archive/zip"
	"bytes"
	"database/sql"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	_ "modernc.org/sqlite"
	"novelhub/pkg/anki"
)

func main() {
	fmt.Println("=== NovelHub Anki Deck Generator Native Probe ===")

	dbFlag := flag.String("db", "", "Path to NovelHub SQLite database (e.g. data/novelhub.db)")
	writeFlag := flag.Bool("write", false, "Write generated sample files to data/ folder")
	outDirFlag := flag.String("out", "data", "Output directory for exported files")
	flag.Parse()

	var cards []anki.Flashcard
	deckName := "NovelHub::The Great Gatsby"
	deckDesc := "Generated by NovelHub Anki Export"

	if *dbFlag != "" {
		fmt.Printf("[*] Loading real highlights from database: %s\n", *dbFlag)
		realCards, bookTitle, err := loadHighlightsFromDB(*dbFlag)
		if err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: Failed to load highlights from DB: %v\n", err)
			os.Exit(1)
		}
		if len(realCards) == 0 {
			fmt.Println("[!] No highlights found in database, using fallback sample cards.")
		} else {
			cards = realCards
			deckName = fmt.Sprintf("NovelHub::%s", bookTitle)
			deckDesc = fmt.Sprintf("Exported from NovelHub Database (%d highlights)", len(cards))
			fmt.Printf("[OK] Loaded %d real highlights from database!\n", len(cards))
		}
	}

	if len(cards) == 0 {
		cards = []anki.Flashcard{
			{
				Front:   "In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever since.",
				Back:    "Opening line introducing Nick Carraway's moral perspective.",
				Context: "The Great Gatsby - Chapter 1 (F. Scott Fitzgerald)",
				Tags:    []string{"NovelHub", "Classics", "Literature"},
			},
			{
				Front:   "Whenever you feel like criticizing anyone, just remember that all the people in this world haven't had the advantages that you've had.",
				Back:    "Nick's father's advice on empathy and privilege.",
				Context: "The Great Gatsby - Chapter 1 (F. Scott Fitzgerald)",
				Tags:    []string{"NovelHub", "Quotes"},
			},
			{
				Front:   "So we beat on, boats against the current, borne back ceaselessly into the past.",
				Back:    "Closing sentence reflecting on human struggle and the American Dream.",
				Context: "The Great Gatsby - Chapter 9 (F. Scott Fitzgerald)",
				Tags:    []string{"NovelHub", "Theme"},
			},
		}
	}

	opts := anki.DeckOptions{
		DeckName:    deckName,
		Description: deckDesc,
	}

	csvContent, err := anki.GenerateCSV(cards)
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: GenerateCSV failed: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("[OK] Generated Anki TSV/CSV (%d bytes, %d cards)\n", len(csvContent), len(cards))

	apkgBytes, err := anki.GenerateApkg(cards, opts)
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: GenerateApkg failed: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("[OK] Generated Anki .apkg (%d bytes)\n", len(apkgBytes))

	zipReader, err := zip.NewReader(bytes.NewReader(apkgBytes), int64(len(apkgBytes)))
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: Failed to open generated .apkg zip: %v\n", err)
		os.Exit(1)
	}

	var anki2Data []byte
	for _, f := range zipReader.File {
		fmt.Printf("  -> Zip Entry: %-20s (Uncompressed: %d bytes)\n", f.Name, f.UncompressedSize64)
		if f.Name == "collection.anki2" {
			rc, _ := f.Open()
			buf := new(bytes.Buffer)
			_, _ = buf.ReadFrom(rc)
			rc.Close()
			anki2Data = buf.Bytes()
		}
	}

	tmpDb, err := os.CreateTemp("", "ankiprobe-*.db")
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: %v\n", err)
		os.Exit(1)
	}
	defer os.Remove(tmpDb.Name())
	_, _ = tmpDb.Write(anki2Data)
	tmpDb.Close()

	db, err := sql.Open("sqlite", tmpDb.Name())
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: Open sqlite failed: %v\n", err)
		os.Exit(1)
	}
	defer db.Close()

	var notesCount, cardsCount int
	_ = db.QueryRow("SELECT count(*) FROM notes").Scan(&notesCount)
	_ = db.QueryRow("SELECT count(*) FROM cards").Scan(&cardsCount)
	fmt.Printf("[OK] Verified Anki Collection SQLite: %d notes, %d cards\n", notesCount, cardsCount)

	if *writeFlag || *dbFlag != "" {
		_ = os.MkdirAll(*outDirFlag, 0755)
		apkgPath := filepath.Join(*outDirFlag, "novelhub_highlights.apkg")
		csvPath := filepath.Join(*outDirFlag, "novelhub_highlights.csv")
		if err := os.WriteFile(apkgPath, apkgBytes, 0644); err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: Failed to write apkg file: %v\n", err)
		} else {
			fmt.Printf("[OK] Saved real Anki package to: %s\n", apkgPath)
		}
		if err := os.WriteFile(csvPath, []byte(csvContent), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: Failed to write csv file: %v\n", err)
		} else {
			fmt.Printf("[OK] Saved real CSV file to: %s\n", csvPath)
		}
	}

	fmt.Println("=== Anki Probe Completed Successfully ===")
}

func loadHighlightsFromDB(dbPath string) ([]anki.Flashcard, string, error) {
	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		return nil, "", err
	}
	defer db.Close()

	query := `
		SELECT h.text_content, COALESCE(h.note, ''), b.title, COALESCE(a.name, ''), COALESCE(c.title, '')
		FROM highlights h
		JOIN books b ON b.id = h.book_id
		LEFT JOIN authors a ON a.id = b.author_id
		LEFT JOIN chapters c ON c.id = h.chapter_id
		ORDER BY h.created_at ASC;
	`
	rows, err := db.Query(query)
	if err != nil {
		return nil, "", err
	}
	defer rows.Close()

	var cards []anki.Flashcard
	bookTitle := "My Library"

	for rows.Next() {
		var text, note, bTitle, author, chapterTitle string
		if err := rows.Scan(&text, &note, &bTitle, &author, &chapterTitle); err != nil {
			return nil, "", err
		}

		if bTitle != "" {
			bookTitle = bTitle
		}

		contextParts := []string{bTitle}
		if chapterTitle != "" {
			contextParts = append(contextParts, chapterTitle)
		}
		if author != "" {
			contextParts = append(contextParts, "("+author+")")
		}

		tag := "NovelHub"
		if bTitle != "" {
			tag = "NovelHub_" + strings.Map(func(r rune) rune {
				if r == ' ' || r == ':' || r == '-' || r == '(' || r == ')' {
					return '_'
				}
				return r
			}, bTitle)
		}

		cards = append(cards, anki.Flashcard{
			Front:   text,
			Back:    note,
			Context: strings.Join(contextParts, " - "),
			Tags:    []string{"NovelHub", tag},
		})
	}

	return cards, bookTitle, nil
}
