CREATE TABLE IF NOT EXISTS reading_goals (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    target_words_per_day INTEGER NOT NULL DEFAULT 1000,
    target_books_per_year INTEGER NOT NULL DEFAULT 12,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
