package services

import (
	"context"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
	"novelhub/internal/dtos/request"
	"novelhub/internal/dtos/response"
	"novelhub/internal/gen/sqlc"
	"novelhub/internal/models"
	"novelhub/internal/repositories"
	"novelhub/pkg/apperrors"
	"novelhub/pkg/constants"
	"novelhub/pkg/convert"
)

type HighlightService interface {
	CreateHighlight(ctx context.Context, userID string, dto *request.CreateHighlightDto, claims *response.JWTClaims) (*response.HighlightResponse, error)
	GetHighlights(ctx context.Context, userID string, chapterID string, claims *response.JWTClaims) ([]*response.HighlightResponse, error)
	UpdateHighlightNote(ctx context.Context, userID string, id string, dto *request.UpdateHighlightNoteDto, claims *response.JWTClaims) (*response.HighlightResponse, error)
	DeleteHighlight(ctx context.Context, userID string, id string, claims *response.JWTClaims) error
}

type highlightService struct {
	repo        repositories.HighlightRepository
	bookRepo    repositories.BookDBRepository
	permissions PermissionCache
}

func NewHighlightService(repo repositories.HighlightRepository, bookRepo repositories.BookDBRepository, permissions PermissionCache) HighlightService {
	return &highlightService{repo: repo, bookRepo: bookRepo, permissions: permissions}
}

// resolveBookIDFromChapterID resolves the bookID for a given chapterID.
// It handles both DB-stored chapters and virtual file-based chapters
// whose IDs follow the "fileID:index" format generated by parseFileChapters.
func (s *highlightService) resolveBookIDFromChapterID(ctx context.Context, chapterID string) (string, bool) {
	// Try DB chapter first
	chapter, err := s.bookRepo.GetChapter(ctx, chapterID)
	if err == nil && chapter != nil {
		return chapter.BookID, true
	}
	// Try virtual chapter format: fileID:index
	lastColon := strings.LastIndex(chapterID, ":")
	if lastColon <= 0 {
		log.Warn().Str("chapter_id", chapterID).Msg("resolveBookIDFromChapterID: not a DB chapter and no ':' separator")
		return "", false
	}
	fileID := chapterID[:lastColon]
	indexStr := chapterID[lastColon+1:]
	if _, err := strconv.Atoi(indexStr); err != nil {
		log.Warn().Str("chapter_id", chapterID).Str("index_str", indexStr).Msg("resolveBookIDFromChapterID: index after ':' is not an integer")
		return "", false
	}
	file, err := s.bookRepo.GetBookFileById(ctx, fileID)
	if err != nil || file == nil {
		log.Warn().Err(err).Str("chapter_id", chapterID).Str("file_id", fileID).Msg("resolveBookIDFromChapterID: GetBookFileById failed")
		return "", false
	}
	return file.BookID, true
}

func (s *highlightService) canHighlight(ctx context.Context, bookID, chapterID string, claims *response.JWTClaims) bool {
	book, err := s.bookRepo.GetBook(ctx, bookID)
	if err != nil || book == nil {
		log.Warn().Err(err).Str("book_id", bookID).Str("chapter_id", chapterID).Msg("highlight.canHighlight: GetBook failed")
		return false
	}
	// Validate chapter belongs to this book (supports both DB and virtual chapters)
	resolvedBookID, ok := s.resolveBookIDFromChapterID(ctx, chapterID)
	if !ok {
		log.Warn().Str("book_id", bookID).Str("chapter_id", chapterID).Msg("highlight.canHighlight: resolveBookIDFromChapterID failed")
		return false
	}
	if resolvedBookID != bookID {
		log.Warn().Str("book_id", bookID).Str("resolved_book_id", resolvedBookID).Str("chapter_id", chapterID).Msg("highlight.canHighlight: resolved bookID mismatch")
		return false
	}
	resolved := resolveClaims(claims)
	attrs := map[string]any{"library_id": book.LibraryID}
	canRead := s.permissions.CanRoles(resolved.RoleIDs, resolved.Roles, constants.PermBookRead, attrs)
	canHighlightPerm := s.permissions.CanRoles(resolved.RoleIDs, resolved.Roles, constants.PermBookHighlight, attrs)
	if !canRead || !canHighlightPerm {
		log.Warn().
			Str("book_id", bookID).Str("chapter_id", chapterID).
			Strs("role_ids", resolved.RoleIDs).
			Strs("roles", roleTypeStrings(resolved.Roles)).
			Str("library_id", book.LibraryID).
			Bool("can_read", canRead).
			Bool("can_highlight", canHighlightPerm).
			Msg("highlight.canHighlight: permission denied")
		return false
	}
	return true
}

// roleTypeStrings converts a slice of RoleType to strings for structured logging.
func roleTypeStrings(roles []constants.RoleType) []string {
	out := make([]string, 0, len(roles))
	for _, r := range roles {
		out = append(out, string(r))
	}
	return out
}

func (s *highlightService) CreateHighlight(ctx context.Context, userID string, dto *request.CreateHighlightDto, claims *response.JWTClaims) (*response.HighlightResponse, error) {
	if dto.StartIndex >= dto.EndIndex {
		return nil, apperrors.New(apperrors.ErrBadRequest, "Invalid text selection range")
	}
	if !s.canHighlight(ctx, dto.BookID, dto.ChapterID, claims) {
		return nil, apperrors.New(apperrors.ErrForbidden, "Highlights are not allowed for this book")
	}

	id := uuid.Must(uuid.NewV7()).String()
	h, err := s.repo.Create(ctx, sqlc.CreateHighlightParams{
		ID:          id,
		UserID:      userID,
		BookID:      dto.BookID,
		ChapterID:   dto.ChapterID,
		TextContent: dto.TextContent,
		StartIndex:  int64(dto.StartIndex),
		EndIndex:    int64(dto.EndIndex),
		Color:       dto.Color,
		Note:        convert.StrPtrToNullString(dto.Note),
	})
	if err != nil {
		return nil, apperrors.New(apperrors.ErrInternalError, "Failed to create highlight")
	}

	return h.ToResponse(), nil
}

func (s *highlightService) GetHighlights(ctx context.Context, userID string, chapterID string, claims *response.JWTClaims) ([]*response.HighlightResponse, error) {
	bookID, ok := s.resolveBookIDFromChapterID(ctx, chapterID)
	if !ok || !s.canHighlight(ctx, bookID, chapterID, claims) {
		return nil, apperrors.New(apperrors.ErrForbidden, "Highlights are not allowed for this chapter")
	}
	highlights, err := s.repo.GetByChapter(ctx, userID, chapterID)
	if err != nil {
		return nil, apperrors.New(apperrors.ErrInternalError, "Failed to get highlights")
	}

	return models.HighlightEntitiesToResponse(highlights), nil
}

func (s *highlightService) UpdateHighlightNote(ctx context.Context, userID string, id string, dto *request.UpdateHighlightNoteDto, claims *response.JWTClaims) (*response.HighlightResponse, error) {
	items, err := s.repo.GetHighlightsByIDs(ctx, []string{id})
	if err != nil || len(items) != 1 || items[0].UserID != userID || !s.canHighlight(ctx, items[0].BookID, items[0].ChapterID, claims) {
		return nil, apperrors.New(apperrors.ErrForbidden, "Highlight is not accessible")
	}
	h, err := s.repo.UpdateNote(ctx, sqlc.UpdateHighlightNoteParams{
		Note:   convert.StrPtrToNullString(dto.Note),
		Color:  dto.Color,
		ID:     id,
		UserID: userID,
	})
	if err != nil {
		return nil, apperrors.New(apperrors.ErrInternalError, "Failed to update highlight note")
	}

	return h.ToResponse(), nil
}

func (s *highlightService) DeleteHighlight(ctx context.Context, userID string, id string, claims *response.JWTClaims) error {
	items, err := s.repo.GetHighlightsByIDs(ctx, []string{id})
	if err != nil || len(items) != 1 || items[0].UserID != userID || !s.canHighlight(ctx, items[0].BookID, items[0].ChapterID, claims) {
		return apperrors.New(apperrors.ErrForbidden, "Highlight is not accessible")
	}
	err = s.repo.Delete(ctx, sqlc.DeleteHighlightParams{
		ID:     id,
		UserID: userID,
	})
	if err != nil {
		return apperrors.New(apperrors.ErrInternalError, "Failed to delete highlight")
	}
	return nil
}
